version: '2.4'
services:
  openresty:
    build:
      context: ./
      dockerfile: Dockerfile-openresty
    restart: always
    ports:
      - 80:80
      - 443:443
    container_name: openresty
    environment:
      - TZ=Asia/Shanghai
